SELECT * FROM Salon;
SELECT * FROM Korisnici;
SELECT * FROM TipNamestaja;
SELECT * FROM Namestaj;
SELECT * FROM DodatneUsluge;
SELECT * FROM Akcije;
SELECT * FROM Racun;
SELECT * FROM ProdatiNamestaj;
SELECT * FROM ProdateUsluge;